# Generated by Django 2.1.5 on 2020-08-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaperForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_form', models.ImageField(upload_to='paper_forms')),
                ('title', models.CharField(blank=True, max_length=100, unique=True)),
            ],
        ),
    ]
