# Generated by Django 2.2.13 on 2020-09-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperform',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
