# Generated by Django 2.2.13 on 2020-09-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formupload', '0002_auto_20200903_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperform',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paperform',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paperform',
            name='is_trash',
            field=models.BooleanField(default=False),
        ),
    ]
