# Generated by Django 2.2.13 on 2020-09-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formupload', '0003_auto_20200914_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperform',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
